'use client';

import { useEffect, Suspense, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { Loader2 } from 'lucide-react';
import { useUser, useFirestore } from '@/firebase';
import { doc, setDoc, collection } from 'firebase/firestore';
import { useToast } from '@/hooks/use-toast';

function TikTokCallback() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const { user, isUserLoading } = useUser();
  const firestore = useFirestore();
  const { toast } = useToast();

  useEffect(() => {
    // Wait until user and firestore are loaded
    if (isUserLoading || !firestore) {
      return;
    }

    const code = searchParams.get('code');
    const state = searchParams.get('state');

    const processCallback = async () => {
      // If there is no user after loading, redirect to login
      if (!user) {
        toast({
            title: "Usuário não encontrado",
            description: "Você precisa estar logado para conectar sua conta.",
            variant: "destructive"
        });
        router.replace('/login');
        return;
      }
      
      // If there is code and state, process the connection
      if (code && state) {
        if (state === '___UNIQUE_STATE_TOKEN_TIKTOK___') {
          try {
            // Create a new document in the subcollection with a random ID
            const tiktokAccountsColRef = collection(firestore, 'users', user.uid, 'tiktokAccounts');
            const newTiktokAccountRef = doc(tiktokAccountsColRef);

            await setDoc(newTiktokAccountRef, {
              id: newTiktokAccountRef.id, // Use the autogenerated ID
              userId: user.uid,
              followerCount: 25000, // Example data
              engagementRate: 0.05, // Example data (5%)
            });

            toast({
              title: "Conta TikTok Conectada!",
              description: "Seus dados foram sincronizados com sucesso.",
            });

          } catch (error) {
            console.error("Erro ao salvar conta do TikTok:", error);
            toast({
              title: "Erro ao salvar conexão",
              description: "Não foi possível salvar os dados da sua conta TikTok.",
              variant: "destructive",
            });
          }
        }
      }
      
      // After processing (or if there is no code), redirect to the connections page
      router.replace('/dashboard/connections');
    };

    processCallback();

  }, [user, isUserLoading, firestore, router, searchParams, toast]);

  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-background">
      <Loader2 className="h-12 w-12 animate-spin text-primary" />
      <p className="mt-4 text-muted-foreground">Finalizando conexão com o TikTok...</p>
    </div>
  );
}

export default function TikTokCallbackPage() {
    return (
        <Suspense fallback={
            <div className="flex flex-col items-center justify-center min-h-screen bg-background">
              <Loader2 className="h-12 w-12 animate-spin text-primary" />
              <p className="mt-4 text-muted-foreground">Carregando...</p>
            </div>
        }>
            <TikTokCallback />
        </Suspense>
    )
}
